/* ============================================================================
   HANNI BEAUTY PALACE — PAYMENT CONFIG
   ============================================================================
   Generated by admin.html → Payment Settings. This is plain text — open it
   in any text editor, or use admin.html to edit it and push it live.

   PAYSTACK_PUBLIC_KEY is safe to expose in the browser (it's the "public"
   key, not the secret key) — it's how the Paystack checkout popup knows
   which Paystack account to charge into.

   VERIFY_PAYMENT_ENDPOINT is the URL script.js calls right after a customer
   pays, to confirm the payment really went through before showing the
   success page. Leave it as '/api/verify-payment' if this site is deployed
   on the same domain as the api/verify-payment.js function; set it to a
   full URL if the function is hosted elsewhere.
   ============================================================================ */

const PAYSTACK_PUBLIC_KEY = "pk_test_REPLACE_WITH_YOUR_PAYSTACK_PUBLIC_KEY";
const VERIFY_PAYMENT_ENDPOINT = "/api/verify-payment";
