/* ============================================================================
   HANNI BEAUTY PALACE — PRODUCT CATALOG
   ============================================================================
   Generated by admin.html. This is plain text — open it in any text editor,
   or use admin.html → product manager to edit it with point-and-click forms
   (and optionally push changes straight to GitHub from there).

   HOW THIS IS USED:
   index.html loads this file (before script.js) and script.js uses
   CATEGORIES + PRODUCTS to render the shop grid, filter pills and service
   tiles. Each product's "icon" and "cat" must match an id in CATEGORIES.
   ============================================================================ */

const CATEGORIES = [
  { id:'skincare',    name:'Organic Skincare',        icon:'leaf' },
  { id:'makeup',      name:'Makeup',                  icon:'lipstick' },
  { id:'cosmetics',   name:'Cosmetics',                icon:'palette' },
  { id:'lash',        name:'Lash & Microblading',      icon:'eye' },
  { id:'nails',       name:'Pedicure & Manicure',      icon:'nail' },
  { id:'facials',     name:'Facials',                  icon:'mask' },
  { id:'massage',     name:'Body Massage & Spa',        icon:'massage' },
  { id:'enhancement', name:'Body Enhancement',          icon:'ribbon' },
  { id:'perfume',     name:'Perfume & Body Spray',      icon:'perfume' },
  { id:'wellness',    name:'Wellness Gifts',            icon:'gift' }
];

const PRODUCTS = [
  { id:1,  name:'Radiance Face Serum',        cat:'skincare',    icon:'leaf',     price:8500,  best:true,  desc:'Vitamin C & botanical blend for an even, dewy glow.', image:'images/vitamin-c-serum.webp' },
  { id:2,  name:'Whipped Shea Body Butter',   cat:'skincare',    icon:'leaf',     price:6000,  best:false, desc:'Deeply nourishing, fragrance-light body butter.', image:'images/shea-butter.webp' },
  { id:3,  name:'Velvet Matte Lip Kit',       cat:'makeup',      icon:'lipstick', price:5500,  best:true,  desc:'Long-wear matte lipstick with a soft liner pencil.', image:'images/lipstick-mauve.webp' },
  { id:4,  name:'Everyday Glow Foundation',   cat:'makeup',      icon:'lipstick', price:9000,  best:false, desc:'Buildable, breathable coverage in a Nigerian shade range.', image:'images/lipstick-mauve.webp' },
  { id:5,  name:'Signature Eyeshadow Palette',cat:'cosmetics',   icon:'palette',  price:7500,  best:false, desc:'12 blendable shades, from soft nude to bold plum.', image:'images/eyeshadow-palette.webp' },
  { id:6,  name:'Luxe Lash Extension Set',    cat:'lash',        icon:'eye',      price:12000, best:true,  desc:'Salon-grade lashes for your next microblading session.', image:'images/lash-kit.webp' },
  { id:7,  name:'Gel Manicure Polish Duo',    cat:'nails',       icon:'nail',     price:7000,  best:false, desc:'Chip-resistant gel colour, two bottles of your choice.', image:'images/nail-polish.webp' },
  { id:8,  name:'Rejuvenating Clay Mask',     cat:'facials',     icon:'mask',     price:4500,  best:true,  desc:'Purifying facial clay for a fresh, even complexion.', image:'images/shea-butter.webp' },
  { id:9,  name:'Relax Massage Oil Blend',    cat:'massage',     icon:'massage',  price:6500,  best:false, desc:'Warm botanical oil used in our signature spa sessions.', image:'images/body-oil-lavender.webp' },
  { id:10, name:'Signature Body Spray Duo',   cat:'perfume',     icon:'perfume',  price:5000,  best:false, desc:'Two long-lasting fragrances, light enough for daily wear.', image:'images/body-oil-lavender.webp' },
  { id:11, name:'Wellness Gift Box',          cat:'wellness',    icon:'gift',     price:10000, best:false, desc:'A curated set of traditional care essentials, beautifully packaged.', image:'images/product-collection.webp' }
];
