/* ============================================================================
   HANNI BEAUTY PALACE — SHIPPING ZONES & FEES
   ============================================================================
   Generated by admin.html. This is plain text — open it in any text editor,
   or keep using admin.html → "Manage Shipping" to edit it with point-and-
   click forms (and optionally push changes straight to GitHub from there).

   HOW THIS IS USED:
   index.html loads this file and uses it to build the "Delivery" dropdown
   at checkout, grouped by "group". The number a customer pays is exactly
   the "fee" value below (in Naira, no commas/symbols).

   FIELD NOTES:
   - group: the optgroup heading shown in the dropdown (e.g. "Abeokuta (Local)").
     Rows are grouped by this automatically — same text = same group.
   - label: the option text (the amount is appended automatically).
   - fee:   the delivery price in Naira. Use 0 for free / pickup options.
   - note (optional): shown as a small note under the dropdown when this
     option is selected.
   ============================================================================ */

const SHIPPING_ZONES = [
  { group: "Abeokuta (Local)", label: "Pickup at Store — Adebiyi Shopping Complex, Adigbe (Free)", fee: 0 },
  { group: "Abeokuta (Local)", label: "Adigbe & Environs Delivery", fee: 1500 },
  { group: "Abeokuta (Local)", label: "Abeokuta Township (Oke-Ilewo, Ita-Oshin, Kuto, Panseke)", fee: 2000 },
  { group: "Abeokuta (Local)", label: "Abeokuta Outskirts (Camp, Obantoko, Asero, Kemta, Onikolobo)", fee: 2500 },

  { group: "Ogun State (Other Towns)", label: "Sango-Ota, Ota, Ifo", fee: 3500 },
  { group: "Ogun State (Other Towns)", label: "Sagamu, Ijebu-Ode, Remo", fee: 4000 },

  { group: "Nigeria (Interstate)", label: "GIG Terminal Pick-up (Interstate)", fee: 6000 },
  { group: "Nigeria (Interstate)", label: "Interstate Home Delivery (all states)", fee: 10000, note: "Fee may be adjusted for bulky or heavy orders." }
];
